# Introduction to Tensors

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Scalars

In [3]:
scalar = torch.tensor(7)
scalar_dimensions = scalar.ndim
print(f"The value of 'scalar' is {scalar} / (Python Data Type: {scalar.item()}) | and it is of {scalar_dimensions} dimensions")

The value of 'scalar' is 7 / (Python Data Type: 7) | and it is of 0 dimensions


- `torch.tensor()` is a method to create tensors in PyTorch
- `scalar.ndim` is an attribute that displays the dimensions of the Tensor/Scalar
- `scalar.item()` is a method to to display the value of the tensor as a Python Data Type *-Instead of the second cell-*
----------------------------------------------------------------------------------------------
`NOTE:` the `scalar.item()` only works for scalar values<br>
As shown above, given that `scalar` has no dimensions, it means that it is rather called a scalar not a tensor

## Vectors

In [5]:
vector = torch.tensor([7,7])
vector_dimensions = vector.ndim
vector_shape = vector.shape
print(
    f"The value of 'vector' is {vector} | and it is of {vector_dimensions} dimensions | and of shape {vector_shape}"
)

The value of 'vector' is tensor([7, 7]) | and it is of 1 dimensions | and of shape torch.Size([2])


As shown above, given that `vector` has a dimension of **[1]**, it means that it is a vector<br>
`NOTE:` Given that `vector` has dimensions we can get its shape now using `vector.shape` attribute

## Matrices

In [6]:
matrix = torch.tensor([[7, 7],[8,8]])
matrix_dimensions = matrix.ndim
matrix_shape = matrix.shape
print(
    f"The value of 'matrix' is: \n{matrix} \n\nand it is of {matrix_dimensions} dimensions | and of shape {matrix_shape}"
)

The value of 'matrix' is: 
tensor([[7, 7],
        [8, 8]]) 

and it is of 2 dimensions | and of shape torch.Size([2, 2])


As shown above, given that `matrix` has a dimension of **[2]**, it means that it is a matrix<br>

## Tensors

In [7]:
my_tensor = torch.tensor([[[7, 7], [8, 8]], [[9, 9], [11, 11]]])
my_tensor_dimensions = my_tensor.ndim
my_tensor_shape = my_tensor.shape
print(
    f"The value of 'my_tensor' is \n{my_tensor} \n\nand it is of {my_tensor_dimensions} dimensions | and of shape {my_tensor_shape}"
)

The value of 'my_tensor' is 
tensor([[[ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [11, 11]]]) 

and it is of 3 dimensions | and of shape torch.Size([2, 2, 2])


As shown above, given that `my_tensor` has a dimension of **[3]**, it means that it is a tensor<br>
`NOTE:` `Tensors` tend to have a dimension of **[3]** or more

# Creating Tensors

In [8]:
rand_tensor = torch.rand(size=(3,3))

- `torch.rand()` function creates a tensor with random values inside it
- `size=()` parameter allows you to specify the size of the tensor *-obviously :D-*

In [9]:
zeros_tensor = torch.zeros(3,3)
ones_tensor = torch.ones(3,3)

- `torch.zeros()` Creates a tensor that contains all zeroes 
- `torch.ones()` Creates a tensor that contains all ones

In [10]:
rand_tensor = torch.rand(3,5)
rand_tensor_dimensions = rand_tensor.ndim
rand_tensor_shape = rand_tensor.shape
print(
    f"The value of 'rand_tensor' is \n{rand_tensor} \n\nand it is of {rand_tensor_dimensions} dimensions | and of shape {rand_tensor_shape}"
)

The value of 'rand_tensor' is 
tensor([[0.8886, 0.0593, 0.0811, 0.6277, 0.9256],
        [0.9168, 0.1673, 0.6940, 0.0186, 0.4753],
        [0.3753, 0.5700, 0.1443, 0.4929, 0.9251]]) 

and it is of 2 dimensions | and of shape torch.Size([3, 5])


In [12]:
ranged_tensor = torch.arange(start=1,end =100, step=8)
ranged_tensor_dimensions = ranged_tensor.ndim
ranged_tensor_shape = ranged_tensor.shape
print(
    f"The value of 'ranged_tensor' is \n{ranged_tensor} \n\nand it is of {ranged_tensor_dimensions} dimensions | and of shape {ranged_tensor_shape}"
)

The value of 'ranged_tensor' is 
tensor([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89, 97]) 

and it is of 1 dimensions | and of shape torch.Size([13])


`torch.arange` Creates a tensor within a specific range
    <br>- *start* -> Starting Number
    <br>- *end* -> Ending Number + 1
    <br>- *step* -> Step Size, meaning how much PyTorch will add in each iterarion

In [13]:
like_tensor = torch.zeros_like(input= my_tensor)
like_tensor_dimensions = like_tensor.ndim
like_tensor_shape = like_tensor.shape
print(
    f"The value of 'like_tensor' is \n{like_tensor} \n\nand it is of {like_tensor_dimensions} dimensions | and of shape {like_tensor_shape}"
)

The value of 'like_tensor' is 
tensor([[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]) 

and it is of 3 dimensions | and of shape torch.Size([2, 2, 2])


`torcch.zeros_like` creates a tensor of zeros that replicates a another tensor's shape

# Creating Advanced Tensors

In [24]:
sample_tensor = torch.tensor(my_tensor.clone().detach(),
                             dtype = int, #! Defines Data tpye
                             device = torch.device("cpu"), #! Defines on where the tensor gets vreated (e.g cpu, gpu, etc.)
                             requires_grad = False, #! For tracking Gradients *TBD*
                             )

sample_tensor_dimensions = sample_tensor.ndim
sample_tensor_shape = sample_tensor.shape
print(
    f"The value of 'sample_tensor' is \n{sample_tensor} \n\nand it is of {sample_tensor_dimensions} dimensions | on {sample_tensor.device} | and of shape {sample_tensor_shape}\n"
)

The value of 'sample_tensor' is 
tensor([[[ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [11, 11]]]) 

and it is of 3 dimensions | on cpu | and of shape torch.Size([2, 2, 2])



/tmp/ipykernel_366490/71318034.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  sample_tensor = torch.tensor(my_tensor.clone().detach(),


When creating a tensor it is recommended to specify the following metrics:<br>
- `dtype` -> The data type of the tensor<br>
- `device` -> The device on which the tensor is stored (e.g CPU, GPU, etc...)<br>
- `requires_grad` -> Whether the tensor requires gradient or not<br>
-----------------------------------------------------------------
`NOTE:` *Operations between two tensor have to be of the same `shape` on the same `device`*