# Tensor Methods

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Tensor Operations

### Original Tensor

In [3]:
original_tensor = torch.rand(size=[5,5],
                       dtype=None,
                       device = "cpu",
                       requires_grad = False,
                       )

original_tensor_dimensions = original_tensor.ndim
original_tensor_shape = original_tensor.shape
print(
    f"The value of 'original_tensor' is \n{original_tensor} \n\nand it is of {original_tensor_dimensions} dimensions | on {original_tensor.device} | and of shape {original_tensor_shape}\n"
)

The value of 'original_tensor' is 
tensor([[0.5475, 0.5703, 0.0017, 0.3808, 0.9596],
        [0.7699, 0.2728, 0.7127, 0.1973, 0.6113],
        [0.6286, 0.1863, 0.5214, 0.2110, 0.1324],
        [0.7573, 0.8776, 0.4667, 0.6067, 0.4764],
        [0.8032, 0.3414, 0.1701, 0.2344, 0.8899]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



### Basic Numerical Operation

In [4]:
added_tensor = original_tensor + 5

added_tensor_dimensions = added_tensor.ndim
added_tensor_shape = added_tensor.shape
print(
    f"The value of 'added_tensor' is \n{added_tensor} \n\nand it is of {added_tensor_dimensions} dimensions | on {added_tensor.device} | and of shape {added_tensor_shape}\n"
)

The value of 'added_tensor' is 
tensor([[5.5475, 5.5703, 5.0017, 5.3808, 5.9596],
        [5.7699, 5.2728, 5.7127, 5.1973, 5.6113],
        [5.6286, 5.1863, 5.5214, 5.2110, 5.1324],
        [5.7573, 5.8776, 5.4667, 5.6067, 5.4764],
        [5.8032, 5.3414, 5.1701, 5.2344, 5.8899]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



In [5]:
subtracted_tensor = original_tensor - 5

subtracted_tensor_dimensions = subtracted_tensor.ndim
subtracted_tensor_shape = subtracted_tensor.shape
print(
    f"The value of 'subtracted_tensor' is \n{subtracted_tensor} \n\nand it is of {subtracted_tensor_dimensions} dimensions | on {subtracted_tensor.device} | and of shape {subtracted_tensor_shape}\n"
)

The value of 'subtracted_tensor' is 
tensor([[-4.4525, -4.4297, -4.9983, -4.6192, -4.0404],
        [-4.2301, -4.7272, -4.2873, -4.8027, -4.3887],
        [-4.3714, -4.8137, -4.4786, -4.7890, -4.8676],
        [-4.2427, -4.1224, -4.5333, -4.3933, -4.5236],
        [-4.1968, -4.6586, -4.8299, -4.7656, -4.1101]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



In [6]:
division_tensor = original_tensor / 5

division_tensor_dimensions = division_tensor.ndim
division_tensor_shape = division_tensor.shape
print(
    f"The value of 'division_tensor' is \n{division_tensor} \n\nand it is of {division_tensor_dimensions} dimensions | on {division_tensor.device} | and of shape {division_tensor_shape}\n"
)

The value of 'division_tensor' is 
tensor([[0.1095, 0.1141, 0.0003, 0.0762, 0.1919],
        [0.1540, 0.0546, 0.1425, 0.0395, 0.1223],
        [0.1257, 0.0373, 0.1043, 0.0422, 0.0265],
        [0.1515, 0.1755, 0.0933, 0.1213, 0.0953],
        [0.1606, 0.0683, 0.0340, 0.0469, 0.1780]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



In [10]:
multiplied_tensor = original_tensor * 5

multiplied_tensor_dimensions = multiplied_tensor.ndim
multiplied_tensor_shape = multiplied_tensor.shape
print(
    f"The value of 'multiplied_tensor' is \n{multiplied_tensor} \n\nand it is of {multiplied_tensor_dimensions} dimensions | on {multiplied_tensor.device} | and of shape {multiplied_tensor_shape}\n"
)

The value of 'multiplied_tensor' is 
tensor([[2.7377, 2.8516, 0.0087, 1.9040, 4.7981],
        [3.8495, 1.3639, 3.5634, 0.9863, 3.0564],
        [3.1428, 0.9313, 2.6071, 1.0550, 0.6618],
        [3.7863, 4.3878, 2.3333, 3.0333, 2.3821],
        [4.0162, 1.7068, 0.8504, 1.1722, 4.4495]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



### Advanced Numerical Operations

In [13]:
elementWise_tensor = torch.mul(original_tensor, added_tensor)

elementWise_tensor_dimensions = elementWise_tensor.ndim
elementWise_tensor_shape = elementWise_tensor.shape
print(
    f"The value of 'elementWise_tensor' is \n{elementWise_tensor} \n\nand it is of {elementWise_tensor_dimensions} dimensions | on {elementWise_tensor.device} | and of shape {elementWise_tensor_shape}\n"
)

The value of 'elementWise_tensor' is 
tensor([[3.0375, 3.1768, 0.0087, 2.0490, 5.7190],
        [4.4423, 1.4384, 4.0713, 1.0252, 3.4301],
        [3.5379, 0.9660, 2.8789, 1.0995, 0.6793],
        [4.3598, 5.1579, 2.5511, 3.4013, 2.6090],
        [4.6614, 1.8233, 0.8794, 1.2271, 5.2414]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



### Element-wise Operation in PyTorch

In the context of PyTorch, an element-wise operation refers to a mathematical operation performed independently on each element of one or more tensors.
- `torch.mul()` is a function in PyTorch used to perform element-wise multiplication between tensors.

----------------------------------------------------------------------------------------------
`NOTE:` The resulting tensor `dot_tensor` is obtained by element-wise multiplication of `original_tensor` and `added_tensor`.

As shown above, the resulting tensor `dot_tensor` has the same dimensions and shape as the input tensors.


In [7]:
cross_tensor = torch.matmul(original_tensor, added_tensor)

cross_tensor_dimensions = cross_tensor.ndim
cross_tensor_shape = cross_tensor.shape
print(
    f"The value of 'cross_tensor' is \n{cross_tensor} \n\nand it is of {cross_tensor_dimensions} dimensions | on {cross_tensor.device} | and of shape {cross_tensor_shape}\n"
)

The value of 'cross_tensor' is 
tensor([[14.0992, 13.4300, 13.0493, 13.0774, 14.2098],
        [14.5395, 13.8476, 13.5829, 13.5799, 14.4574],
        [ 9.4794,  9.1348,  8.9247,  8.9432,  9.4024],
        [18.1485, 17.3760, 17.1570, 16.9625, 17.9607],
        [13.8969, 13.2874, 12.7891, 12.9549, 14.1006]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



### Matrix Multiplication (torch.matmul) in PyTorch

In PyTorch, matrix multiplication is performed using the `torch.matmul()` function. This function computes the matrix product of two tensors, which is different from element-wise multiplication.

Matrix multiplication involves multiplying the rows of the first matrix with the columns of the second matrix to produce a new matrix. The dimensions of the matrices must satisfy certain requirements for the multiplication to be valid:

---------------------------------------

- `NOTE:` The number of columns in the first matrix must equal the number of rows in the second matrix.
- `NOTE:` If matrix1 has shape `(m, n)` and `matrix2` has shape `(n, p)`, then the resulting matrix, `result_matrix`, will have a shape of `(m, p)`.

In [8]:
transposed_tensor = cross_tensor.T

transposed_tensor_dimensions = transposed_tensor.ndim
transposed_tensor_shape = transposed_tensor.shape
print(
    f"The value of 'transposed_tensor' is \n{transposed_tensor} \n\nand it is of {transposed_tensor_dimensions} dimensions | on {transposed_tensor.device} | and of shape {transposed_tensor_shape}\n"
)

The value of 'transposed_tensor' is 
tensor([[14.0992, 14.5395,  9.4794, 18.1485, 13.8969],
        [13.4300, 13.8476,  9.1348, 17.3760, 13.2874],
        [13.0493, 13.5829,  8.9247, 17.1570, 12.7891],
        [13.0774, 13.5799,  8.9432, 16.9625, 12.9549],
        [14.2098, 14.4574,  9.4024, 17.9607, 14.1006]]) 

and it is of 2 dimensions | on cpu | and of shape torch.Size([5, 5])



### Transposing a Tensor in PyTorch

In PyTorch, transposing a tensor involves rearranging its dimensions. This operation swaps the dimensions of the tensor, effectively flipping its shape.

For example, if a tensor has dimensions `(m, n)`, transposing it will result in a tensor with dimensions `(n, m)`, where the rows become columns and vice versa.

# Tensor Aggregations

In [9]:
tensor_max = transposed_tensor.max()
tensor_min = transposed_tensor.min()
tensor_mean = transposed_tensor.mean()
tensor_sum = transposed_tensor.sum()

print(f"Max number in `transposed_tensor` is {tensor_max}.")
print(f"Min number in `transposed_tensor` is {tensor_min}.")
print(f"Mean of numbers in `transposed_tensor` is {tensor_mean}.")
print(f"Sum of all numbers in `transposed_tensor` is {tensor_sum}.")

Max number in `transposed_tensor` is 18.148517608642578.
Min number in `transposed_tensor` is 8.924700736999512.
Mean of numbers in `transposed_tensor` is 13.53564739227295.
Sum of all numbers in `transposed_tensor` is 338.39117431640625.


- `tensor.max()` returns the highest value in the tensor
- `tensor.min()` returns the smallest value in the tensor
- `tensor.mean()` returns the avg value in the tensor
- `tensor.sum()` returns the sum of all the values in the tensor
----------------------------------------------------------------------------------------------
`NOTE:` the `tensor.mean()` only works for float data types<br>